---
kind: Service
apiVersion: v1
metadata:
  name: doks-example
  namespace: test
spec:
  selector:
    app: doks-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doks-example
  template:
    metadata:
      labels:
        app: doks-example
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: doks-route
  namespace: test
spec:
  host: doks-route-default.apps.ocp.home
  to:
    kind: Service
    name: doks-example
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
