apiVersion: v1
kind: Service
metadata:
  name: color
  labels:
    app: color
    app.kubernetes.io/name: color
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: color
spec:
  ports:
  - name: http
    port: 8080
  selector:
    name: color
  sessionAffinity: None
  type: ClusterIP
