apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/data/"
          name: test-pvc
