kind: Namespace
apiVersion: v1
metadata:
  name: simple-app
  labels:
    kubernetes.io/metadata.name: simple-app
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
