apiVersion: v1
kind: Secret
metadata:
  labels:
    app: server
    app.kubernetes.io/name: productdb
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: productdb
    app.kubernetes.io/part-of: product-catalog
  name: productdb
stringData:
  database-name: productdb
  database-password: Demo1234
  database-root-password: Demo1234
  database-user: productdb
